import { mkdir, writeFile, readFile } from "fs/promises";
import { join, dirname } from "path";
import { homedir } from "os";
import type { ParsedSession, SessionSummary, State } from "./types.js";
import { getConfig } from "./config.js";

/**
 * Ensure output directories exist
 */
export async function ensureOutputDir(projectSlug: string): Promise<string> {
  const config = await getConfig();
  const projectDir = join(config.output.directory, projectSlug);
  await mkdir(projectDir, { recursive: true });
  return projectDir;
}

/**
 * Create a filename-safe slug from text
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50);
}

/**
 * Generate markdown content from session and summary
 */
export function generateMarkdown(
  session: ParsedSession,
  summary: SessionSummary
): string {
  const lines: string[] = [];
  const date = session.startTime.toISOString().split("T")[0];

  // Frontmatter
  lines.push("---");
  lines.push(`date: ${date}`);
  lines.push(`project: ${session.projectSlug}`);
  lines.push(`session: ${session.sessionId}`);
  if (summary.filesChanged.length > 0) {
    lines.push(
      `files: [${summary.filesChanged.map((f) => f.path).join(", ")}]`
    );
  }
  lines.push("---");
  lines.push("");

  // Title
  lines.push(`# ${summary.title}`);
  lines.push("");

  // Metadata
  lines.push(`**Date:** ${date}`);
  lines.push(`**Project:** ${session.project}`);
  lines.push(`**Session:** ${session.sessionId}`);
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push("");
  lines.push(summary.summary);
  lines.push("");

  // What was done
  if (summary.whatWasDone.length > 0) {
    lines.push("## What Was Done");
    lines.push("");
    for (const item of summary.whatWasDone) {
      lines.push(`- ${item}`);
    }
    lines.push("");
  }

  // Files changed
  if (summary.filesChanged.length > 0) {
    lines.push("## Files Changed");
    lines.push("");
    for (const file of summary.filesChanged) {
      lines.push(`- \`${file.path}\` - ${file.change}`);
    }
    lines.push("");
  }

  // Decisions
  if (summary.decisions.length > 0) {
    lines.push("## Key Decisions");
    lines.push("");
    for (const decision of summary.decisions) {
      lines.push(`- **${decision.decision}**: ${decision.reasoning}`);
    }
    lines.push("");
  }

  // Errors
  if (summary.errors.length > 0) {
    lines.push("## Errors Encountered");
    lines.push("");
    for (const error of summary.errors) {
      lines.push(`- ${error}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by cc-worklog*");

  return lines.join("\n");
}

/**
 * Write session summary to markdown file
 */
export async function writeSessionMarkdown(
  session: ParsedSession,
  summary: SessionSummary
): Promise<string> {
  const projectDir = await ensureOutputDir(session.projectSlug);
  const date = session.startTime.toISOString().split("T")[0];
  const shortId = session.sessionId.slice(0, 6);
  const titleSlug = slugify(summary.title);

  const filename = `${date}_${shortId}_${titleSlug}.md`;
  const filepath = join(projectDir, filename);

  const content = generateMarkdown(session, summary);
  await writeFile(filepath, content, "utf-8");

  return filepath;
}

/**
 * Load state from file
 */
export async function loadState(): Promise<State> {
  const config = await getConfig();
  const stateFile = join(config.state.directory, "state.json");
  try {
    await mkdir(config.state.directory, { recursive: true });
    const content = await readFile(stateFile, "utf-8");
    return JSON.parse(content) as State;
  } catch {
    return { processed: {} };
  }
}

/**
 * Save state to file
 */
export async function saveState(state: State): Promise<void> {
  const config = await getConfig();
  const stateFile = join(config.state.directory, "state.json");
  await mkdir(config.state.directory, { recursive: true });
  await writeFile(stateFile, JSON.stringify(state, null, 2), "utf-8");
}

/**
 * Mark a session as processed
 */
export async function markProcessed(
  sessionId: string,
  outputFile: string
): Promise<void> {
  const state = await loadState();
  state.processed[sessionId] = {
    processedAt: new Date().toISOString(),
    outputFile,
  };
  await saveState(state);
}
